/**
 * bm_fonts.h — extern declarations for the project's u8g2 fonts.
 *
 * The .c definitions in Core/Src/fonts/ are autogenerated by upstream
 * bdfconv from scripts/build-fonts.sh; do NOT edit them. To change the
 * glyph set or swap source BDFs, edit the script and re-run.
 *
 * Three fonts at three sizes, all carrying the full printable-ASCII
 * subset (32-126, 95 glyphs each). Pick whichever fits the space; the
 * names below describe size, not a usage constraint.
 *
 *   bm_font_18b  — 9x18 bold mono. Chunky headline numbers and any
 *                  other place that wants big, attention-grabbing
 *                  text (a "FAULT" banner, the V/A readout).
 *   bm_font_15b  — 9x15 bold mono. Medium-weight labels. Sized so a
 *                  string on the left of the panel visually matches a
 *                  bm_font_18b reading on the right.
 *   bm_font_5x7  — 5x7 fixed mono. Compact tray / status text, unit
 *                  suffixes, anything that has to share a row.
 *
 * Total packed cost ~3 KB FLASH at 95 glyphs each. See
 * scripts/build-fonts.sh for the per-font source BDF + invocation.
 */

#ifndef BM_FONTS_H
#define BM_FONTS_H

#include "u8g2.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t bm_font_18b[]  U8G2_FONT_SECTION("bm_font_18b");
extern const uint8_t bm_font_15b[]  U8G2_FONT_SECTION("bm_font_15b");
extern const uint8_t bm_font_5x7[]  U8G2_FONT_SECTION("bm_font_5x7");

#ifdef __cplusplus
}
#endif

#endif /* BM_FONTS_H */
