/**
 * bm_fonts.h — extern declarations for the project's custom-subset u8g2 fonts.
 *
 * The .c definitions in Core/Src/fonts/ are autogenerated by upstream
 * bdfconv from scripts/build-fonts.sh; do NOT edit them. To change the
 * glyph set or source BDF, edit the script and re-run.
 *
 * Glyph subsets (see build-fonts.sh for the exact -m maps):
 *   bm_big_digits   — '-./0-9' + space, 14 glyphs, 9x18 bold mono.
 *                     Headline V / A readout on the top half.
 *   bm_small_status — '%-./0-9:A-Z' + space, 42 glyphs, 5x7 fixed mono.
 *                     Bottom-row status (K1/BLD/T/FAN/state labels).
 */

#ifndef BM_FONTS_H
#define BM_FONTS_H

#include "u8g2.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t bm_big_digits[]   U8G2_FONT_SECTION("bm_big_digits");
extern const uint8_t bm_small_status[] U8G2_FONT_SECTION("bm_small_status");

#ifdef __cplusplus
}
#endif

#endif /* BM_FONTS_H */
