#!/usr/bin/env bash
# build-fonts.sh — regenerate the project's u8g2 fonts under Core/Src/fonts/.
#
# u8g2's stock fonts are vendored as one 39 MB mega-file we explicitly
# excluded from Middlewares/u8g2/ (see VERSION.txt). Instead, this script
# builds upstream bdfconv on demand, points it at our chosen BDF source
# fonts from u8g2's tools/font/bdf/ tree, and emits packed u8g2 font
# arrays sized to the printable ASCII subset (32-126, 95 glyphs each).
#
# An earlier version of this script trimmed each font to only the glyphs
# in use at the time (~14-68 glyphs each, ~1.4 KB total). Measured cost
# of moving to full printable ASCII was ~+1.5 KB FLASH for ~135 extra
# glyphs across three fonts — cheap enough that the engineering win of
# "any new screen / label just works" beats the footprint savings.
#
# Usage (Windows host, project root):
#     wsl bash scripts/build-fonts.sh
#
# Or directly in WSL / Linux from the project root:
#     bash scripts/build-fonts.sh
#
# Requires: bash, curl, tar, gcc, make. Already installed by setup-wsl.sh.
#
# The generated .c files ARE checked in. Re-run this only when:
#   - bumping the u8g2 vendored version (update U8G2_VERSION below)
#   - changing the source BDF font (edit the bdfconv invocation)
#   - intentionally narrowing the glyph set again to claw back FLASH

set -euo pipefail

U8G2_VERSION="${U8G2_VERSION:-2.36.19}"

# Resolve project root regardless of where the script is invoked from.
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$PROJECT_ROOT/Core/Src/fonts"

WORK="$(mktemp -d -t u8g2-fonts-XXXX)"
trap 'rm -rf "$WORK"' EXIT

echo "==> Building custom-subset u8g2 fonts (upstream $U8G2_VERSION)"
echo "    Output: $OUT_DIR"
mkdir -p "$OUT_DIR"

echo ""
echo "==> [1/3] Downloading u8g2 source tarball"
TARBALL="$WORK/u8g2.tar.gz"
curl -fsSL -o "$TARBALL" \
    "https://github.com/olikraus/u8g2/archive/refs/tags/${U8G2_VERSION}.tar.gz"

echo ""
echo "==> [2/3] Extracting tools/font/ and building bdfconv"
# Only need tools/font/ — bdfconv source + the BDF font corpus. Skip the rest
# (sys/arm-linux/drivers has a symlink that breaks tar without --skip-errors).
tar -xzf "$TARBALL" -C "$WORK" \
    --wildcards "u8g2-${U8G2_VERSION}/tools/font/*"

BDFCONV_DIR="$WORK/u8g2-${U8G2_VERSION}/tools/font/bdfconv"
BDF_DIR="$WORK/u8g2-${U8G2_VERSION}/tools/font/bdf"
( cd "$BDFCONV_DIR" && make -j 2>&1 | tail -3 )
BDFCONV="$BDFCONV_DIR/bdfconv"

echo ""
echo "==> [3/3] Generating fonts"

# bdfconv's output starts directly with the `const uint8_t ...` declaration —
# no #include line, so the file fails to compile standalone. Wrap each
# generated file with the u8g2.h include + a doc header pointing at this
# script. Done as a post-process to keep the bdfconv invocation simple.
prepend_include() {
    local file=$1
    local tmp="${file}.tmp"
    {
        echo "/*"
        echo " * Auto-generated by scripts/build-fonts.sh from u8g2 ${U8G2_VERSION}."
        echo " * Do not edit by hand. Re-run the script to regenerate."
        echo " */"
        echo "#include \"u8g2.h\""
        echo ""
        cat "$file"
    } > "$tmp"
    mv "$tmp" "$file"
}

# --- bm_big_digits ------------------------------------------------------
# Headline V / A readout on the 128x32 OLED — and any other place that
# wants chunky bold characters (e.g. a future "FAULT" banner).
# Glyphs: full printable ASCII 32-126.
# Source: 9x18B — 9x18 bold monospace, 18 px tall, 9 px wide. Fits 12-14
# chars across the 128 px panel with margin. Proven X11 font.
echo "    bm_big_digits   <- 9x18B.bdf, glyphs: printable ASCII (32-126)"
"$BDFCONV" -v -f 1 -m '32-126' \
    -n bm_big_digits \
    -o "$OUT_DIR/bm_big_digits.c" \
    "$BDF_DIR/9x18B.bdf"
prepend_include "$OUT_DIR/bm_big_digits.c"

# --- bm_state_label -----------------------------------------------------
# Headline status label ("Charging" / "No Batt" / "Trickle" / etc.).
# Sized to visually match the bm_big_digits headline weight on the right
# side of the panel — 15 px tall is ~83% of the 18 px digits, close
# enough that the two halves don't look mismatched.
# Glyphs: full printable ASCII 32-126.
# Source: 9x15B  — bold mono 9x15.
echo "    bm_state_label  <- 9x15B.bdf, glyphs: printable ASCII (32-126)"
"$BDFCONV" -v -f 1 -m '32-126' \
    -n bm_state_label \
    -o "$OUT_DIR/bm_state_label.c" \
    "$BDF_DIR/9x15B.bdf"
prepend_include "$OUT_DIR/bm_state_label.c"

# --- bm_small_status ----------------------------------------------------
# Bottom tray (charge timer + F/K/B indicators), V/A unit suffixes next
# to the big-digit reading, and any future "details" text that has to
# fit in a tight row.
# Glyphs: full printable ASCII 32-126.
# Source: 5x7 — 5x7 fixed monospace. Fits ~25 chars across at 7 px tall,
# leaves ~25 px headroom in the 32 px panel for the headline.
echo "    bm_small_status <- 5x7.bdf, glyphs: printable ASCII (32-126)"
"$BDFCONV" -v -f 1 -m '32-126' \
    -n bm_small_status \
    -o "$OUT_DIR/bm_small_status.c" \
    "$BDF_DIR/5x7.bdf"
prepend_include "$OUT_DIR/bm_small_status.c"

echo ""
echo "==> Done. Generated:"
ls -la "$OUT_DIR"/*.c
echo ""
echo "Add/commit the .c files under Core/Src/fonts/. Re-run this script only"
echo "when the glyph set, source font, or u8g2 version changes."
