#!/usr/bin/env python3
"""Run clang-tidy on hand-written embedded C in BatteryMonitorV2.

Uses compile_commands.json from a build directory (default: build/Debug, with
fallbacks to build/ci-Debug / build/Release / build/ci-Release). Targets only
the files we authored or substantially modified; CubeMX boilerplate, TinyUSB,
FreeRTOS, and HAL drivers are intentionally excluded.

Usage:
    python scripts/lint.py                          # lint with auto-detected build dir
    python scripts/lint.py --fix                    # apply --fix-errors where safe
    python scripts/lint.py --build-dir build/Debug  # explicit build dir
    python scripts/lint.py --warnings-as-errors     # CI mode: any warning fails

Exit codes:
    0 — clean
    1 — warnings or errors found
    2 — tooling / invocation error
"""
from __future__ import annotations

import argparse
import platform
import shutil
import subprocess
import sys
from pathlib import Path

# Lint coverage is greedy: every .c under Core/Src/ is linted EXCEPT the
# CubeMX-generated peripheral init / HAL scaffolding / newlib stubs / font
# tables enumerated below. New hand-written modules dropped into Core/Src/
# get picked up automatically — no need to edit this file (or the
# matching check_tests.py manifest that imports LINT_FILES) every time.
# If a new file shouldn't be linted (CubeMX regen, autogenerated table,
# vendor drop), add it to LINT_EXCLUDE with a brief reason.
LINT_EXCLUDE = {
    # CubeMX peripheral init — bodies are regenerated; only the USER CODE
    # blocks are ours, and lint warnings on the surrounding scaffolding
    # would just be noise.
    "Core/Src/main.c",
    "Core/Src/adc.c",
    "Core/Src/crc.c",
    "Core/Src/dma.c",
    "Core/Src/dmamux.c",
    "Core/Src/flash.c",
    "Core/Src/gpio.c",
    "Core/Src/i2c.c",
    "Core/Src/tim.c",
    "Core/Src/usart.c",
    "Core/Src/usb.c",
    # HAL MSP / system / timebase — CubeMX-managed.
    "Core/Src/stm32c0xx_hal_msp.c",
    "Core/Src/stm32c0xx_hal_timebase_tim.c",
    "Core/Src/system_stm32c0xx.c",
    # newlib retarget stubs — toolchain-provided defaults, not ours.
    "Core/Src/syscalls.c",
    "Core/Src/sysmem.c",
}


def _discover_lint_files() -> list[str]:
    """Return every Core/Src/**/*.c that isn't in LINT_EXCLUDE and isn't
    under an autogenerated subdirectory (fonts/). Sorted for determinism."""
    project_root = Path(__file__).parent.parent
    src_dir = project_root / "Core" / "Src"
    files: list[str] = []
    for p in sorted(src_dir.rglob("*.c")):
        rel = p.relative_to(project_root).as_posix()
        if rel.startswith("Core/Src/fonts/"):
            continue  # autogenerated by scripts/build-fonts.sh
        if rel in LINT_EXCLUDE:
            continue
        files.append(rel)
    return files


LINT_FILES = _discover_lint_files()

BUILD_DIR_FALLBACKS = ["build/Debug", "build/ci-Debug", "build/Release", "build/ci-Release"]


def print_install_help() -> None:
    """Print platform-specific install instructions for clang-tidy."""
    system = platform.system()
    print("error: clang-tidy not on PATH.", file=sys.stderr)
    print("", file=sys.stderr)
    print("Install options:", file=sys.stderr)
    if system == "Windows":
        print("  Recommended: use WSL (matches CI exactly).", file=sys.stderr)
        print("    wsl bash scripts/setup-wsl.sh    # one-time", file=sys.stderr)
        print("    wsl bash scripts/run-lint.sh     # day-to-day", file=sys.stderr)
        print("  Or via CMake:  cmake --build build/<preset> --target lint", file=sys.stderr)
        print("  Or via VS Code: Tasks -> 'Lint (clang-tidy, WSL)'", file=sys.stderr)
        print("", file=sys.stderr)
        print("  Native Windows clang-tidy (winget/choco) won't work — it", file=sys.stderr)
        print("  can't cross-compile arm-none-eabi without the ARM LLVM headers.", file=sys.stderr)
    elif system == "Linux":
        print("  sudo apt install clang-tidy   # Debian/Ubuntu", file=sys.stderr)
        print("  sudo dnf install clang-tools-extra   # Fedora", file=sys.stderr)
        print("  sudo pacman -S clang   # Arch", file=sys.stderr)
    elif system == "Darwin":
        print("  brew install llvm", file=sys.stderr)
        print("  Then add to PATH: $(brew --prefix llvm)/bin", file=sys.stderr)
    else:
        print(f"  (unknown platform: {system}) — install LLVM clang-tidy from your package manager", file=sys.stderr)


def find_clang_tidy(override: str | None) -> str | None:
    if override:
        return override if Path(override).is_file() else shutil.which(override)
    return shutil.which("clang-tidy")


def find_build_dir(override: str | None) -> Path | None:
    if override:
        p = Path(override)
        return p if (p / "compile_commands.json").is_file() else None
    for d in BUILD_DIR_FALLBACKS:
        p = Path(d)
        if (p / "compile_commands.json").is_file():
            return p
    return None


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--build-dir", help="dir containing compile_commands.json")
    p.add_argument("--tidy", help="clang-tidy executable (else: search PATH)")
    p.add_argument("--fix", action="store_true", help="apply --fix-errors")
    p.add_argument("--warnings-as-errors", action="store_true",
                   help="treat any warning as an error (CI mode)")
    p.add_argument("--extra-arg", action="append", default=[],
                   help="passed through to clang-tidy (repeatable). Useful for "
                        "--extra-arg=-resource-dir=... when crossing toolchains.")
    args = p.parse_args()

    tidy = find_clang_tidy(args.tidy)
    if not tidy:
        print_install_help()
        return 2

    build_dir = find_build_dir(args.build_dir)
    if not build_dir:
        searched = args.build_dir or " | ".join(BUILD_DIR_FALLBACKS)
        print(f"error: no compile_commands.json found in: {searched}", file=sys.stderr)
        print("Run a CMake configure first (CMake Tools build button, or", file=sys.stderr)
        print("`cmake --preset Debug` from the firmware project root).", file=sys.stderr)
        return 2

    cmd = [tidy, "-p", str(build_dir)]
    if args.fix:
        cmd.append("--fix-errors")
    if args.warnings_as_errors:
        cmd.append("--warnings-as-errors=*")
    for extra in args.extra_arg:
        cmd.append(f"--extra-arg={extra}")
    cmd.extend(LINT_FILES)

    print(f"$ clang-tidy -p {build_dir} [{len(LINT_FILES)} files]")
    result = subprocess.run(cmd)
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
