/*
 * Auto-generated by scripts/build-fonts.sh from u8g2 2.36.19.
 * Do not edit by hand. Re-run the script to regenerate.
 */
#include "u8g2.h"

/*
  Fontname: -Misc-Fixed-Bold-R-Normal--18-120-100-100-C-90-ISO10646-1
  Copyright: Public domain font.  Share and enjoy.
  Glyphs: 14/762
  BBX Build Mode: 0
*/
const uint8_t bm_big_digits[203] U8G2_FONT_SECTION("bm_big_digits") = 
  "\16\0\3\3\4\4\3\5\5\10\16\0\0\16\374\16\374\0\0\0\0\0\256 \5\0\364\31-\6\27\245"
  "\31\7.\6#\207\31\6/\15\250\204\331R\261TY\252,\25\3\60\15\247\205Y\63\211\32\337$j"
  "#\0\61\15\250\204y\322!M\42\326\333!\0\62\14\247\205Y\63\211\232TQ\307\3\63\15\247\205\31"
  "W\241\342X\225$\42\1\64\20\247\205\231\302\31I\242$\21I\216R\25\0\65\15\247\205\31\7\251j"
  "Y\225$\42\1\66\20\247\205Y$\241TZR\221\321$j#\0\67\15\247\205\31W\241T(\25J"
  "\265\1\70\21\247\205Y\63\211\232Dm&Q\243I\324F\0\71\20\247\205Y\63\211\32M\42\31U\25"
  "E$\0\0\0\0\4\377\377\0";
